name: Build and Test (Galactic)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: galactic
      - name: Build and Test rm_auto_aim
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: rm_auto_aim
          import-token: ${{ secrets.GITHUB_TOKEN }}
          target-ros2-distro: galactic
